In [2]:
import numpy as np

In [3]:
list=[1,2,3,4,5]
# list=[1,2,3,4,5]
np.array(list)

array([1, 2, 3, 4, 5])

# Numpy Built-in Methods
### 1. arange - just like range in python
### 2. zeros and ones
### 3. linespaces - return evenly spaced numbers over a specified interval
### 4. eye - creates an identity matrix
### 5. Random (rand,randint,randn) Rand used for uniform distribution and randn is used for 'Standard Normal' distribution
### 6. .max(),.min(),.argmax(),argmin()


In [14]:
print(np.arange(1,10,2))
print(np.zeros(2))
print(np.zeros((2,2)))
print(np.zeros((2,2,3)))



[0. 0.]
[[0. 0.]
 [0. 0.]]
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [17]:
print(np.ones(2))
print(np.ones((2,2)))
print(np.ones((2,2,3)))



[1. 1.]
[[1. 1.]
 [1. 1.]]
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [23]:
ndarray=np.linspace(1,2,50).reshape(5,10)
print(ndarray.ndim)
print(ndarray.shape)
print(ndarray.dtype)
print(ndarray.size)
print(ndarray.itemsize)


2
(5, 10)
float64
50
8


In [19]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [24]:
print(np.random.randint(1,100))
np.random.rand(2)
np.random.rand(5,5)
np.random.randn(2)
np.random.randint(1,100,10)






54


# Numpy Indexing and Slicing
#### 1. Indexing
#### 2. Slicing
#### 3. Broadcasting
#### 4. Setting a copy of an array



In [27]:
arr=np.linspace(1,10,10)

In [29]:
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [30]:
arr[arr>4]

array([ 5.,  6.,  7.,  8.,  9., 10.])

# Numpy Operations

In [32]:
arr+arr

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [33]:
arr*arr

array([  1.,   4.,   9.,  16.,  25.,  36.,  49.,  64.,  81., 100.])

In [34]:
arr/arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [35]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [36]:
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [37]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [38]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])